version: 1
update_configs:
  # Keep package.json (& lockfiles) secure and up-to-date,
  # batching pull requests daily
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"